[package]
name = "reason"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bitflags = "2.4.1"
limine = "0.1.12"
spin = "0.9.8"

[build-dependencies]
walkdir = "2"
nasm-rs = "0.2"

